import type { RecurringExpense, RecurringExpenseFilter, RecurringFrequency, RecurringPaymentMethod, RenewalMode } from './recurring-expenses-types';

export const recurringExpenseFilters: readonly { id: RecurringExpenseFilter; label: string }[] = [
  { id: 'all', label: 'الكل' },
  { id: 'upcoming', label: 'مستحقة قريبًا' },
  { id: 'subscriptions', label: 'اشتراكات' },
  { id: 'operational', label: 'التزامات تشغيلية' },
  { id: 'paused', label: 'متوقفة' },
  { id: 'needs-review', label: 'تحتاج مراجعة' },
];

export const recurringFrequencyOptions: readonly { id: RecurringFrequency; label: string }[] = [
  { id: 'weekly', label: 'أسبوعي' },
  { id: 'monthly', label: 'شهري' },
  { id: 'bimonthly', label: 'كل شهرين' },
  { id: 'quarterly', label: 'ربع سنوي' },
  { id: 'semiannual', label: 'نصف سنوي' },
  { id: 'annual', label: 'سنوي' },
  { id: 'custom', label: 'مخصص' },
];

export const renewalModeOptions: readonly { id: RenewalMode; label: string }[] = [
  { id: 'automatic', label: 'تلقائي' },
  { id: 'manual', label: 'يدوي' },
];

export const paymentMethodOptions: readonly { id: RecurringPaymentMethod; label: string }[] = [
  { id: 'company-card', label: 'بطاقة الشركة' },
  { id: 'bank-account', label: 'حساب بنكي' },
  { id: 'cash', label: 'نقدي' },
  { id: 'transfer', label: 'تحويل' },
  { id: 'other', label: 'أخرى' },
];

export const reminderOptions: readonly { value: string; label: string }[] = [
  { value: '', label: 'بدون تذكير' },
  { value: '3', label: 'قبل 3 أيام' },
  { value: '7', label: 'قبل 7 أيام' },
  { value: '14', label: 'قبل 14 يومًا' },
  { value: '30', label: 'قبل 30 يومًا' },
];

export const prototypeCurrency = 'ر.س';

export const initialRecurringExpenses: RecurringExpense[] = [
  {
    id: 'design-tools',
    name: 'أدوات التصميم',
    vendor: 'Adobe',
    description: 'اشتراك أدوات التصميم والإنتاج الإبداعي.',
    categoryId: 'expense-software',
    amount: 420,
    currency: prototypeCurrency,
    frequency: 'monthly',
    startDate: '2026-01-10',
    nextDueDate: '2026-08-10',
    renewalMode: 'automatic',
    paymentMethod: 'company-card',
    accountId: 'حساب الأعمال',
    owner: 'فريق التصميم',
    reminderDays: 7,
    status: 'active',
    usageLevel: 'مرتفع',
    needsReview: false,
    notes: 'أداة أساسية في سير العمل اليومي.',
    payments: [
      { id: 'pay-design-2026-07', date: '2026-07-10', amount: 420, method: 'company-card', status: 'paid' },
      { id: 'pay-design-2026-06', date: '2026-06-10', amount: 420, method: 'company-card', status: 'paid' },
      { id: 'pay-design-2026-05', date: '2026-05-10', amount: 420, method: 'company-card', status: 'paid' },
    ],
    createdAt: '2026-01-10',
    updatedAt: '2026-07-10',
  },
  {
    id: 'cloud-hosting',
    name: 'استضافة الخوادم',
    vendor: 'مزود سحابي',
    description: 'خوادم الإنتاج والنسخ الاحتياطية.',
    categoryId: 'expense-operations',
    amount: 2850,
    currency: prototypeCurrency,
    frequency: 'monthly',
    startDate: '2026-02-03',
    nextDueDate: '2026-08-03',
    renewalMode: 'automatic',
    paymentMethod: 'company-card',
    accountId: 'حساب الأعمال',
    owner: 'فريق التقنية',
    reminderDays: 7,
    status: 'active',
    usageLevel: 'مرتفع',
    needsReview: false,
    payments: [
      { id: 'pay-hosting-2026-07', date: '2026-07-03', amount: 2850, method: 'company-card', status: 'paid' },
      { id: 'pay-hosting-2026-06', date: '2026-06-03', amount: 2850, method: 'company-card', status: 'paid' },
    ],
    createdAt: '2026-02-03',
    updatedAt: '2026-07-03',
  },
  {
    id: 'office-rent',
    name: 'إيجار المكتب',
    vendor: 'مالك العقار',
    description: 'إيجار المساحة التشغيلية الحالية.',
    categoryId: 'expense-rent',
    amount: 12000,
    currency: prototypeCurrency,
    frequency: 'monthly',
    startDate: '2026-01-01',
    nextDueDate: '2026-08-01',
    renewalMode: 'manual',
    paymentMethod: 'transfer',
    accountId: 'حساب الأعمال',
    owner: 'العمليات',
    reminderDays: 7,
    status: 'active',
    needsReview: false,
    payments: [
      { id: 'pay-rent-2026-07', date: '2026-07-01', amount: 12000, method: 'transfer', status: 'paid' },
      { id: 'pay-rent-2026-06', date: '2026-06-01', amount: 12000, method: 'transfer', status: 'paid' },
    ],
    createdAt: '2026-01-01',
    updatedAt: '2026-07-01',
  },
  {
    id: 'payroll',
    name: 'رواتب الفريق',
    vendor: 'الموظفون',
    categoryId: 'expense-salaries',
    amount: 28000,
    currency: prototypeCurrency,
    frequency: 'monthly',
    startDate: '2026-01-28',
    nextDueDate: '2026-07-28',
    renewalMode: 'manual',
    paymentMethod: 'bank-account',
    accountId: 'حساب الأعمال',
    owner: 'المؤسس',
    reminderDays: 3,
    status: 'active',
    needsReview: false,
    payments: [
      { id: 'pay-payroll-2026-06', date: '2026-06-28', amount: 28000, method: 'bank-account', status: 'paid' },
      { id: 'pay-payroll-2026-05', date: '2026-05-28', amount: 28000, method: 'bank-account', status: 'paid' },
    ],
    createdAt: '2026-01-28',
    updatedAt: '2026-06-28',
  },
  {
    id: 'crm',
    name: 'نظام إدارة العملاء',
    vendor: 'مزود CRM',
    description: 'إدارة العملاء المحتملين والمتابعات.',
    categoryId: 'expense-software',
    amount: 1250,
    currency: prototypeCurrency,
    frequency: 'monthly',
    startDate: '2026-03-05',
    nextDueDate: '2026-08-05',
    renewalMode: 'automatic',
    paymentMethod: 'company-card',
    accountId: 'بطاقة الشركة',
    owner: 'فريق المبيعات',
    reminderDays: 7,
    status: 'active',
    usageLevel: 'منخفض',
    needsReview: true,
    reviewReason: 'الاستخدام منخفض مقارنة بالتكلفة الشهرية.',
    monthlySavingOpportunity: 750,
    payments: [
      { id: 'pay-crm-2026-07', date: '2026-07-05', amount: 1250, method: 'company-card', status: 'paid' },
      { id: 'pay-crm-2026-06', date: '2026-06-05', amount: 1250, method: 'company-card', status: 'paid' },
      { id: 'pay-crm-2026-05', date: '2026-05-05', amount: 1250, method: 'company-card', status: 'paid' },
    ],
    createdAt: '2026-03-05',
    updatedAt: '2026-07-05',
  },
  {
    id: 'meeting-tool',
    name: 'منصة الاجتماعات',
    vendor: 'مزود اجتماعات',
    categoryId: 'expense-software',
    amount: 530,
    currency: prototypeCurrency,
    frequency: 'monthly',
    startDate: '2026-02-12',
    nextDueDate: '2026-08-12',
    renewalMode: 'automatic',
    paymentMethod: 'company-card',
    accountId: 'بطاقة الشركة',
    owner: 'فريق العمليات',
    reminderDays: 7,
    status: 'active',
    usageLevel: 'منخفض',
    needsReview: true,
    reviewReason: 'يوجد تداخل مع أدوات اجتماعات أخرى ضمن الفريق.',
    monthlySavingOpportunity: 530,
    payments: [
      { id: 'pay-meeting-2026-07', date: '2026-07-12', amount: 530, method: 'company-card', status: 'paid' },
      { id: 'pay-meeting-2026-06', date: '2026-06-12', amount: 530, method: 'company-card', status: 'paid' },
    ],
    createdAt: '2026-02-12',
    updatedAt: '2026-07-12',
  },
  {
    id: 'health-insurance',
    name: 'التأمين الطبي',
    vendor: 'شركة التأمين',
    categoryId: 'expense-other',
    amount: 18000,
    currency: prototypeCurrency,
    frequency: 'annual',
    startDate: '2025-11-01',
    nextDueDate: '2026-11-01',
    renewalMode: 'manual',
    paymentMethod: 'transfer',
    accountId: 'حساب الأعمال',
    owner: 'الموارد البشرية',
    reminderDays: 30,
    status: 'active',
    needsReview: false,
    payments: [{ id: 'pay-insurance-2025-11', date: '2025-11-01', amount: 18000, method: 'transfer', status: 'paid' }],
    createdAt: '2025-11-01',
    updatedAt: '2025-11-01',
  },
  {
    id: 'legal-retainer',
    name: 'الاستشارة القانونية',
    vendor: 'مكتب قانوني',
    categoryId: 'expense-professional',
    amount: 3000,
    currency: prototypeCurrency,
    frequency: 'quarterly',
    startDate: '2026-03-01',
    nextDueDate: '2026-09-01',
    renewalMode: 'manual',
    paymentMethod: 'transfer',
    accountId: 'حساب الأعمال',
    owner: 'المؤسس',
    reminderDays: 14,
    status: 'active',
    needsReview: false,
    payments: [
      { id: 'pay-legal-2026-06', date: '2026-06-01', amount: 3000, method: 'transfer', status: 'paid' },
      { id: 'pay-legal-2026-03', date: '2026-03-01', amount: 3000, method: 'transfer', status: 'paid' },
    ],
    createdAt: '2026-03-01',
    updatedAt: '2026-06-01',
  },
  {
    id: 'old-analytics',
    name: 'أداة تحليلات قديمة',
    vendor: 'مزود تحليلات',
    description: 'تم إيقاف الاشتراك بعد اعتماد بديل داخلي.',
    categoryId: 'expense-software',
    amount: 600,
    currency: prototypeCurrency,
    frequency: 'monthly',
    startDate: '2025-12-20',
    renewalMode: 'automatic',
    paymentMethod: 'company-card',
    accountId: 'بطاقة الشركة',
    owner: 'فريق التقنية',
    status: 'paused',
    pausedAt: '2026-06-20',
    usageLevel: 'منخفض',
    needsReview: false,
    payments: [
      { id: 'pay-analytics-2026-06', date: '2026-06-20', amount: 600, method: 'company-card', status: 'paid' },
      { id: 'pay-analytics-2026-05', date: '2026-05-20', amount: 600, method: 'company-card', status: 'paid' },
    ],
    createdAt: '2025-12-20',
    updatedAt: '2026-06-20',
  },
];
